This tutorial walks you through using the HaloAnalysis package to read and use halo catalogs generated by Rockstar and merger trees generated via ConsistentTrees, from Gizmo simulations.

@author: Andrew Wetzel <arwetzel@gmail.com>

First, move within a simulation directory that contains a sub-directory 'halo/' that in turn contains a directory named rockstar/ or rockstar_dm/. (By convention, rockstar/ implies that Rockstar halo finding ran using all particle species, dark matter + stars + gas, while rockstar_dm/ implies that Rockstar halo finding ran using only dark-matter particles, which can produce more stable behavior.) By default, this HaloAnalysis package assumes that the raw text files that Rockstar produces have been converted to hdf5 format files that are in halo/rockstar_dm/catalog_hdf5/.

Currently we run Rockstar halo finder using only dark-matter particles. This means that all halo quantities are computed using **only** dark-matter particles. Within halo/rockstar_dm/catalog_hdf5/, halo_*.hdf5 (one file per snapshot) and tree.hdf5 (one file across all snapshots) thus contain halo information based only on dark-matter particles.

HaloAnalysis can assign baryonic (star or gas) particles to dark-matter halos in post-processing. By default, HaloAnalysis stores these properties for stars in files named catalog_hdf5/star_*.hdf5, with 1 file per snapshot. By default, the HaloAnalysis reader looks for these star files, and if they exist, it assigns those properties to the halo catalogs or trees when you read them. You can disable this, to read only dark-matter halo properties for speed/efficiency, by setting species=None in read_catalogs() or read_tree().

Ensure that the halo_analysis and utilities directories are in your python path, then...

In [1]:
import halo_analysis as halo
import utilities as ut

import numpy as np

In [2]:
# you can access the individual files/modules as named or use the aliases in __init__.py for convenience/brevity. for example, these are the same:

halo.halo_io
halo.io

<module 'halo_analysis.halo_io' from '/jonathan_storage/shtainer/anaconda3/envs/guyenv/lib/python3.11/site-packages/halo_analysis/halo_io.py'>

# read halo catalog

In [ ]:
simulation_directory = 'Sims/m12i_res7100'
hal = halo.io.IO.read_catalogs('redshift', 0, simulation_directory)
for k in hal.keys():
    print(k)

In [3]:
# we recommend that you copy this jupyter notebook tutorial into a simulation directory 
# (for example, m12i_res7100/) and run from there.
# however, you can set simulation_directory below to point to any simulation directory and then run this notebook from anywhere

# use this is you are running from within a simulation directory
#simulation_directory = '.'

# use this to point to a specific simulation directory, if you run this notebook from somwhere else
simulation_directory = 'Sims/m12i_res7100'

In [4]:
# read a halo catalog at single snapshot (z = 0)

hal = halo.io.IO.read_catalogs('redshift', 0, simulation_directory)


# in utilities.simulation.Snapshot():
* reading:  Sims/m12i_res7100/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000


# in halo_analysis.halo_io.IO():
* read 35838 halos from:  Sims/m12i_res7100/halo/rockstar_dm/catalog_hdf5/halo_600.hdf5

# in halo_analysis.halo_io.Particle():
* read 35838 halos, 55 have star particles, from:  Sims/m12i_res7100/halo/rockstar_dm/catalog_hdf5/star_600.hdf5
* assigning primary host and coordinates wrt it to halo catalog...  finished



In [14]:
# hal is a dictionary of halo properties

for k in hal.keys():
    print(k)
# print(hal['position'][27714])
print(hal['radius'])
index = hal['host.index'][0]
print(index)
# print(hal['host.velocity'])
# print(np.linalg.norm(hal['velocity'][index]))
print(hal['star.mass'])
print(hal['radius'][index])
print(hal['star.radius.90'])
print(hal.prop('star.radius.50')[index])

accrete.rate
accrete.rate.100Myr
accrete.rate.tdyn
am.phantom
am.progenitor.main
axis.b/a
axis.c/a
descendant.id
descendant.snapshot
id
infall.first.mass
infall.first.snapshot
infall.first.vel.circ.max
infall.mass
infall.snapshot
infall.vel.circ.max
major.merger.snapshot
mass
mass.180m
mass.200c
mass.200m
mass.500c
mass.bound
mass.half.snapshot
mass.lowres
mass.peak
mass.peak.snapshot
mass.vir
position
position.offset
progenitor.number
radius
scale.radius
scale.radius.klypin
spin.bullock
spin.peebles
tree.index
vel.circ.max
vel.circ.peak
vel.std
velocity
velocity.offset
dark2.mass
star.form.time.100
star.form.time.50
star.form.time.90
star.form.time.95
star.form.time.dif.68
star.indices
star.mass
star.massfraction
star.number
star.position
star.radius.50
star.radius.90
star.vel.std
star.vel.std.50
star.velocity
host.index
host.distance
host.velocity
host.velocity.tan
host.velocity.rad
[15.269231   3.002849   2.7293448 ...  2.9173791  3.5313392  2.5099714]
27728
[-1. -1. -1. ... -1. -1.

In [ ]:
# read halo catalogs at all available snapshots by supplying None or 'all' as the input snapshot value.
# read_catalogs() returns this as a list of dictionaries, with the list index being the snapshot index.
# beware - this can take a while to read...

hals = halo.io.IO.read_catalogs('redshift', None, simulation_directory)

In [ ]:
# halo catalog at z = 0 (snapshot 600)
hal_z0 = hals[600]

# halo catalog at z = 1 (snapshot 277)
hal_z1 = hals[277]

In [ ]:
# else, you can read just a few specific snapshots
# by default, it stores them in a (mostly emply) list, so the halo catalog list index = snapshot index

hals = halo.io.IO.read_catalogs('redshift', [0, 1], simulation_directory)

# halo catalog at z = 0 (snapshot 600)
hal_z0 = hals[600]

# halo catalog at z = 1 (snapshot 277)
hal_z1 = hals[277]

In [ ]:
# alternately, if you want a compact list (so halo catalog list index != snapshot index)

hals = halo.io.IO.read_catalogs('redshift', [0, 1], simulation_directory, all_snapshot_list=False)

hal_z1 = hals[0]
hal_z0 = hals[1]

# halo properties

In [76]:
# read halo catalog at z = 0

hal = halo.io.IO.read_catalogs('redshift', 0, simulation_directory,assign_species_pointers=False,assign_hosts_rotation=False)


# in utilities.simulation.Snapshot():
* reading:  Sims/m12i_res7100/snapshot_times.txt

* input redshift = 0:  using snapshot index = 600, redshift = 0.000

* read 35833 halos from:  Sims/m12i_res7100/halo/rockstar_dm/catalog_hdf5/halo_600.hdf5

# in halo_analysis.halo_io.Particle():
* read 35833 halos, 55 have star particles, from:  Sims/m12i_res7100/halo/rockstar_dm/catalog_hdf5/star_600.hdf5
* assigning primary host and coordinates wrt it to halo catalog...  finished



In [ ]:
# hal is a dictionary of halo properties

for k in hal.keys():
    print(k)

In [20]:
# 3-D position (particle_number x dimension_number array) [kpc comoving]

hal['position']

array([[40282.48 , 44150.8  , 44975.156],
       [41644.66 , 44150.97 , 45904.188],
       [40424.117, 43417.42 , 45033.918],
       ...,
       [42363.32 , 46332.01 , 46921.266],
       [42393.12 , 46323.58 , 47001.668],
       [42379.375, 46329.13 , 47020.586]], dtype=float32)

In [11]:
# 3-D velocity (particle_number x dimension_number array) [km/s physical]

len(hal['velocity'])

35838

In [ ]:
# DM mass of halo [M_sun]
# by default, I run the halo finder using 200m (200 x the mean matter density) for the default overdensity/virial definition

hal['mass']

In [ ]:
# but Rockstar also stores halo DM mass based on different virial definitions [M_sun]

print('{}\n{}\n{}'.format(hal['mass.200m'], hal['mass.vir'], hal['mass.200c']))

In [ ]:
# DM mass that is bound to halo [M_sun]

hal['mass.bound']

In [ ]:
# halo radius [kpc physical] again using 200m for the overdensity/virial definition 

hal['radius']

In [ ]:
# NFW scale radius [kpc physical]

hal['scale.radius']

In [ ]:
# maximum of the circular velocity profile [km/s physical]

hal['vel.circ.max']

In [ ]:
# standard deviation of the velocity (velocity dispersion) [km/s physical]

hal['vel.std']

In [ ]:
# the fraction of DM mass within R_200m that is low-resolution DM
# this is a derived quantity, so you need to call via the .prop() function (see below)

hal.prop('lowres.mass.frac')

In [92]:
# index of the primary (most massive) host halo in the catalog

hal['host.index']

array([27714, 27714, 27714, ..., 27714, 27714, 27714], dtype=int32)

In [93]:
# 3-D distance to the primary host halo [kpc physical]

hal['host.distance']

array([[-1509.6875  ,    19.589844, -1292.5273  ],
       [ -147.50781 ,    19.757812,  -363.4961  ],
       [-1368.0508  ,  -713.78906 , -1233.7656  ],
       ...,
       [  571.15234 ,  2200.8008  ,   653.58203 ],
       [  600.9531  ,  2192.3672  ,   733.9844  ],
       [  587.20703 ,  2197.918   ,   752.90234 ]], dtype=float32)

In [ ]:
# total (scalar) distance to the primary host halo [kpc physical]
# this is a derived quantity, so you need to call via the .prop() function (see below)

hal.prop('host.distance.total')

In [9]:
# 3-D velocity wrt the primary host halo [kpc physical]
# radial and tangential velocity wrt the primary host halo [kpc physical]

print(len(hal['host.velocity']))
print(hal['host.velocity.rad'])
print(hal['host.velocity.tan'])

35838
[117.28903  -45.474136  38.652447 ... 252.45824  257.7575   282.78857 ]
[ 47.294292 121.6347    83.525475 ... 154.76328  149.34566  145.04024 ]


In [8]:
# use .prop() to compute derived quantities
# this can handle simple arithmetic conversions, such as the log of the mass, or the ratio of masses
# see halo.io.HaloDictionaryClass for all options for derived quantities

print(hal.prop('host.distance.total'))
print(hal.prop('host.velocity.total'))
print(hal.prop('log mass'))
print(hal.prop('mass.bound / mass'))

[1987.5027   392.7828   508.78168 ... 3098.3235  3109.43    3116.8428 ]
[126.46528 129.85722  92.03541 ... 296.11963 297.89767 317.81448]
[8.0467205 6.00871   5.8685293 ... 6.064821  6.1483674 5.9612794]
[0.9962135  0.8275809  0.8571456  ... 0.6666749  0.97500706 0.53846633]


# halo catalogs with baryonic particle properties

HaloAnalysis can assign baryonic (star or gas) particle properties to dark-matter halos in post-processing after generating the dark-matter halo catalogs. This package stores these baryonic properties in separate files, such as star_600.hdf5 for star particles at snapshot 600.

By default, the HaloAnalysis reader automatically looks if star files exist at a snapshot that you read, and it will read and append these star properties to the halo catalog. You can disable this if you want to read only dark-matter halo properties for speed/efficiency, by setting species=None in read_catalogs().

In [ ]:
# explicit input to ensure that it reads star particle properties for each halo

hal = halo.io.IO.read_catalogs('redshift', 0, simulation_directory, species='star')

In [ ]:
# all stellar properties have dictionary keys as 'star.*'
# list of star particle properties
for k in hal:
    if 'star.' in k:
        print(k)

In [6]:
# find halos with star particles

hindices = np.where(hal['star.mass'] > 0)[0]
print(hindices)
print(len(hindices))

[  411   454  4986  5103  5471  5501  5545  5591  7113  8520  9157  9191
  9208 13591 14366 14442 14449 14450 14488 14604 14764 14766 14851 20277
 20412 20505 20658 23758 23916 24153 24158 24653 24694 27026 27240 27711
 27722 27728 27744 27750 27815 30577 30693 31138 31229 31544 32204 32210
 32221 32227 32242 32436 35102 35198 35826]
55


In [10]:
# mass of all star particles in halo [M_sun]

hal['star.mass'][hindices]
print(hal['star.number'][hindices])
print(hal['star.position'][hindices])
print(hal['star.mass'][hindices])
print(hal['star.position'][27722])

[       4       39       20       12        9       48      186       32
        5     1706    24554        2        9        4       15     1219
        4        5    12850        2        9        4     8717       12
      692       26        3        6        6       45        7        6
        6        5       19       10       45 10374329      498      146
        4        3       10        5       36      143        3     2100
        3        7        2     4566        4   604884        2]
[[41260.645 43860.21  45594.215]
 [41307.742 43869.16  45575.44 ]
 [41573.78  44033.668 46076.805]
 [41680.59  44022.99  46195.055]
 [41686.043 44000.453 46244.52 ]
 [41780.805 44145.6   46103.945]
 [41735.375 44075.258 46207.19 ]
 [41779.5   43470.152 46636.266]
 [41667.793 43852.074 46307.08 ]
 [41601.785 43937.992 46488.527]
 [41609.527 43988.918 46287.586]
 [41677.38  44090.234 46275.98 ]
 [41780.984 44093.094 46295.79 ]
 [41742.46  44276.72  46047.91 ]
 [41756.43  44453.44  46189.293]
 [

In [88]:
# number of star particles in halo [M_sun]
# hindices = np.where(hal['star.mass'] > 0)[0]
# hindices = [406, 442, 4993, 5113, 5488, 5512, 5556, 5611, 7125, 8549, 9171, 9205, 9224, 13374, 14373, 14450, 14457, 14464, 14496, 14603, 14766, 14768, 14856, 20287, 20430, 20515, 20670, 23777, 23928, 24170, 24528, 24665, 24706, 27027, 27227, 27696, 27702, 27735, 27747, 27824, 30682, 31078, 31107, 31220, 31540, 32381, 32387, 32394, 32404, 32415, 32429, 35571, 35712]
# values_to_remove = [27714,35801]
# for value_to_remove in values_to_remove:
#     hindices = hindices[hindices != value_to_remove].tolist()
#     print("removed ",value_to_remove)
#     print(hindices)
print(hal['star.number'][hindices])
# print(np.sum(hal['star.number'][hindices]))
max = 0 
for i in range(len(hindices)):
    if hal['star.number'][hindices[i]] > max:
        max = hal['star.number'][hindices[i]]
        max_index = hindices[i]
        max_index_place = i
print(max_index)
print(max_index_place)
print(hal['position'][hindices[max_index_place]])
print(hal[

[       4       39       20       12        9       48      194       32
        5     1706    24548        2        9        4       15     1219
        4        5    12855        2        9        4     8717       12
      692       26        3        6        6        7       45        6
        6        5       19      498      146 10374006       10       45
        4       10        3        5       36      143        3     2100
        7        3     4561        2        2        4   604941]
11036824
27714
37
[41792.168 44131.21  46267.684]


In [42]:
# radius that encloses 50%, 90% of the stellar mass [kpc physical]

print(hal['star.radius.50'][hindices])
print(hal['star.radius.90'][hindices])

[ 0.5333236   0.6972131   1.54911     1.5886506   1.4568827   1.1611174
  2.862703    0.9523848   0.6033851   1.8503612   1.9853864   0.29040226
  0.68949896  2.21818     0.9875799   2.9760711   1.2475697   1.9079114
  4.5857797   0.46773514  0.50058925  1.9860953   2.719826    1.1612644
  1.6487899   1.4422022   1.2548972   0.5188739   0.98408777  0.7952358
  1.1468757   0.8932328   0.6207329   1.5615152   0.90678555  1.2270805
  1.1455171   2.843102    2.3390954   1.0624295   1.0399603   0.9841623
  0.8862909   2.2307787   0.8750106   1.1594003   1.0246439   1.7667097
  0.74726164  0.50414675  2.6730254  10.864256    1.2793813   0.6500967
  4.9147816 ]
[ 2.0493605   1.3834529   3.0762267   5.6856256   2.208444    3.743317
  4.7526717   2.3371537   1.2633519   4.2304235   4.7499747   0.29705992
  1.1120878   5.7361627   2.2258134   8.996271    1.4609437   2.9009104
 10.084518    0.48735264  0.7692258   2.6891632   7.2203927   1.971488
  4.728445    2.7272365   1.7528518   0.7436903   

In [43]:
# derived property: stellar density (within R_50) as a derived property [M_sun / kpc^3]

hal.prop('star.density.50', hindices)

array([1.6809070e+04, 7.0279500e+04, 3.1900840e+03, 1.8086295e+03,
       1.8051661e+03, 1.8816445e+04, 4.7554697e+03, 2.1959832e+04,
       1.2960604e+04, 1.6218592e+05, 1.8922719e+06, 4.5923191e+04,
       1.5908162e+04, 2.2799588e+02, 9.2227705e+03, 2.7397541e+04,
       1.2049576e+03, 4.2427356e+02, 7.9888102e+04, 1.1256575e+04,
       4.8581770e+04, 3.0459659e+02, 2.6094311e+05, 4.7739673e+03,
       9.0815172e+04, 5.3457456e+03, 8.9696320e+02, 2.6282549e+04,
       3.9168596e+03, 8.5775244e+03, 1.7504781e+04, 4.9367925e+03,
       1.6135859e+04, 8.0991150e+02, 1.4814775e+04, 1.5753734e+05,
       5.6105008e+04, 3.2677405e+08, 4.6554935e+02, 2.1716012e+04,
       2.1532173e+03, 6.1549048e+03, 2.6508918e+03, 2.8602264e+02,
       3.2598756e+04, 5.4552957e+04, 1.5850698e+03, 2.2068706e+05,
       9.9226201e+03, 1.3449355e+04, 1.4036105e+05, 9.4916368e-01,
       5.7856738e+02, 8.8327236e+03, 3.3099408e+06], dtype=float32)

In [ ]:
# stellar velocity dispersion (standard deviation) at R_50 [km / s]

hal['star.vel.std.50'][hindices]

In [12]:
# center-of-mass position and velocity of star particles [kpc comoving]

print(hal['star.position'][hindices])
print(hal['star.velocity'][hindices])

[[41260.645 43860.21  45594.215]
 [41307.742 43869.16  45575.44 ]
 [41573.78  44033.668 46076.805]
 [41680.59  44022.99  46195.055]
 [41686.043 44000.453 46244.52 ]
 [41780.805 44145.6   46103.945]
 [41735.375 44075.258 46207.19 ]
 [41779.5   43470.152 46636.266]
 [41667.793 43852.074 46307.08 ]
 [41601.785 43937.992 46488.527]
 [41609.527 43988.918 46287.586]
 [41677.38  44090.234 46275.98 ]
 [41780.984 44093.094 46295.79 ]
 [41742.46  44276.72  46047.91 ]
 [41756.43  44453.44  46189.293]
 [41663.434 44175.883 46309.26 ]
 [41743.434 44181.664 46200.812]
 [41754.34  44173.945 46206.67 ]
 [41744.613 44258.37  46182.184]
 [41486.637 44983.074 47179.43 ]
 [41526.207 45096.273 47185.098]
 [41546.29  45119.977 47191.152]
 [41674.32  44333.883 46627.016]
 [41584.95  44166.73  46373.86 ]
 [41712.977 44486.113 46374.156]
 [42136.758 42365.89  46094.566]
 [42123.684 42349.277 45944.42 ]
 [41956.613 42671.566 46137.438]
 [41868.477 44061.883 46010.492]
 [41880.086 44117.42  46118.363]
 [41912.72

In [ ]:
# time (age of Universe) when galaxy formed 50%, 90%, etc of its current stellar mass [Gyr]

print(hal['star.form.time.50'][hindices])
print(hal['star.form.time.90'][hindices])
print(hal['star.form.time.95'][hindices])
print(hal['star.form.time.100'][hindices])

In [ ]:
# convert this to lookback-time via a derived property [Gyr]

hal.prop('star.form.time.lookback.50', hindices)

In [ ]:
# indices of member star particles
# for example, star particles assigned to halo 0 would be part_indices = hal['star.indies'][0]
# then if you read in the star particles in the snapshot file, you can access member star particles via 
# part['star'][property_name][part_indices]

hal['star.indices'][hindices[0]]

If you are reading halos at some snapshot at z > 0, and if the GizmoAnalysis package already generated baryonic particle pointers for tracking baryonic particles between any snapshot at z > 0 and the snapshot at z = 0, you additionally can store the pointer indices from member baryonic particles in each halo at z > 0 to the particle catalog at z = 0 by setting assign_species_pointers=True as follows.

There are no pointers at the snapshot at z = 0, becuase it would point to itself. 

In [ ]:
hal = halo.io.IO.read_catalogs('redshift', 1, simulation_directory, species='star', assign_species_pointers=True)

In [ ]:
hindices = np.where(hal['star.mass'] > 0)[0]

# indices of member star particles in the particle catalog at this snapshot
print(hal['star.indices'][hindices[3]])

# indices of member star particles in the particle catalog at the final snapshot at z = 0
# in other words, where these member star particles end up in the particle array at z = 0
print(hal['star.z0.indices'][hindices[3]])

# additional information stored in sub-dictionaries

In [79]:
# dictionary of useful information about the simulation

hal.info

{'dark.particle.mass': 35181.05413105413,
 'box.length/h': 60000.0,
 'box.length': 85470.08547008547,
 'catalog.kind': 'halo.catalog',
 'file.kind': 'hdf5',
 'has.baryons': True,
 'host.number': 1,
 'simulation.name': 'm12i r7100',
 'gas.particle.mass': 7067.275774670917}

In [91]:
hal.host
hal.info

{'rotation': [], 'axis.ratios': []}

In [80]:
# dictionary class of information about the cosmology of the simulation

hal.Cosmology

{'omega_lambda': 0.728,
 'omega_matter': 0.272,
 'omega_baryon': 0.0455,
 'omega_curvature': 0.0,
 'omega_dm': 0.22650000000000003,
 'baryon.fraction': 0.16727941176470587,
 'hubble': 0.7020000000000001,
 'sigma_8': 0.807,
 'n_s': 0.961,
 'w': -1.0}

In [81]:
# dictionary of information about this snapshot's index, scale-factor, redshift, time, lookback-time

hal.snapshot

{'index': 600,
 'scalefactor': 1.0,
 'redshift': 0.0,
 'time': 13.798746883488608,
 'time.lookback': 0.0,
 'time.hubble': 13.92866412650697}

In [82]:
# dictionary of arrays about *all* snapshots of the simulation

print(hal.Snapshot.keys())
print(hal.Snapshot['redshift'])

dict_keys(['scalefactor.spacing', 'cosmology', 'verbose', 'index', 'scalefactor', 'redshift', 'time', 'time.lookback', 'time.width'])
[9.90000000e+01 1.90000000e+01 1.50000000e+01 1.46059065e+01
 1.42307606e+01 1.38732500e+01 1.35321169e+01 1.32062807e+01
 1.28947353e+01 1.25965633e+01 1.23109179e+01 1.20370445e+01
 1.17741976e+01 1.15217409e+01 1.12790689e+01 1.10456238e+01
 1.08208895e+01 1.06044016e+01 1.03956871e+01 1.01943474e+01
 9.99999905e+00 9.81967735e+00 9.64516067e+00 9.47619533e+00
 9.31250000e+00 9.15385151e+00 9.00000000e+00 8.84375000e+00
 8.69230843e+00 8.54545498e+00 8.40298557e+00 8.26470661e+00
 8.13043499e+00 8.00000095e+00 7.86153984e+00 7.72727585e+00
 7.59701824e+00 7.47058487e+00 7.34782410e+00 7.22856998e+00
 7.11267471e+00 7.00000000e+00 6.89743424e+00 6.79746580e+00
 6.70000172e+00 6.60493898e+00 6.51219416e+00 6.42168474e+00
 6.33333540e+00 6.24705935e+00 6.16279030e+00 6.08045816e+00
 6.00000191e+00 5.92307854e+00 5.84782839e+00 5.77419615e+00
 5.70212984e

# halo merger trees

The halo finder treats each snapshot as an independent catalog, so halos at different snapshots do not know about each other. ConsistentTrees produces halo merger trees that link halos over time.

ConsistentTrees applies some smoothing and physical consistency checks on halos over time, which leads to two important differences from the halo catalog: (1) not every halo in the catalog exists in the merger tree (especially those that are only marginally resolved) (2) some halos in the merger tree are 'phantom' halos that have been interpolated across snapshots but do not exist in the halo catalog at that snapshot.

As with the halo catalogs, the HaloAnalysis reader can check for files that contain baryonic (star or gas) particle properies at each snapshot, and it can read and append these baryonic properties to the halo merger trees. Unlike reading a halo catalog at a single snapshot, HaloAnalysis disables this feature by default when reading the merger trees, because it requires reading in about 600 hdf5 files and thus can be slow. To enable it, set species='star' in read_tree().

In [ ]:
# read halo merger trees across all snapshots
# this is a concatenated array of all halos across all snaphots, with pointers to progenitor and descendant halos

halt = halo.io.IO.read_tree(simulation_directory=simulation_directory)

In [ ]:
# read halo merger trees across all snapshots and read member star particle files at each snapshot
# this may take a while...

halt = halo.io.IO.read_tree(simulation_directory=simulation_directory, species='star')

In [ ]:
# if you only want to read star particle information at one or a few snapshots, you can specify which ones, which significantly speeds up the read time!
# for example, read star particles information only at snapshot 277 (z = 1) and 600 (z = 0)

halt = halo.io.IO.read_tree(simulation_directory=simulation_directory, species='star', species_snapshot_indices=[277, 600])

In [ ]:
# read halo merger trees across all snapshots and read member star particles and pointer files at select snapshots

halt = halo.io.IO.read_tree(simulation_directory=simulation_directory, species='star', species_snapshot_indices=[277, 600], assign_species_pointers=True)

In [ ]:
# halt is a dictionary of halo merger tree properties

for k in halt.keys():
    print(k)

In [ ]:
# each halo has its snapshot index (remember that the tree contains all halos at every snapshot)

halt['snapshot']

In [ ]:
# get all halos at snapshot 600 (z = 0) and print their masses

hindices = np.where(halt['snapshot'] == 600)[0]
print(halt['mass'][hindices])

In [ ]:
# get indices of member star particles at snapshot 277 and pointers tot their indices at z = 0 (snapshot 600)
hindices = np.where(halt['star.mass'] > 0)[0]
hindices = ut.array.get_indices(halt['snapshot'], 277, hindices)
hindex = hindices[10]

print(halt['star.indices'][hindex])
print(halt['star.z0.indices'][hindex])

In [ ]:
# alternately, get catalog of halos only at snapshot 600 from tree

hal = halo.io.IO.get_catalog_from_tree(halt, 600)

In [ ]:
# flag of whether halo is 'phantom' interpolation across snapshots

halt['am.phantom']

In [ ]:
# get the tree index of a halo's descendant at a later (usually the next) snapshot
# a negative value means that a halo does not have a descendant
# ConsistentTrees allows only one descendant per halo

print(halt['descendant.index'])

# for example, get descendant of halo index 100 and print its mass
hindex = 100
desc_index = halt['descendant.index'][hindex]
print(desc_index, halt['mass'][desc_index])

In [ ]:
# number of progenitor halos (can be arbitrarily large) at an earler (usually the previous) snapshot
# a negative value means that a halo does not have a progenitor

halt['progenitor.number']

In [ ]:
# tree index of main (most massive) progenitor
# loop over this to get list of main progenitors going back in time

halt['progenitor.main.index']

In [ ]:
# whether I am the main (most massive) progenitor of my descendant

halt['am.progenitor.main']

In [ ]:
# tree index of next co-progenitor

halt['progenitor.co.index']

In [ ]:
# tree index of my descendant at the final snapshot (z = 0)

halt['final.index']

In [ ]:
# example of walking the merger tree
# find all progenitors and list their masses

# start with a halo with tree index 0 (at z = 0)
hindex = 0
print(halt['snapshot'][hindex])
print(halt['mass'][hindex])

# find its progenitors, list their mass
prog_index = halt['progenitor.main.index'][hindex]
prog_indices = []
while prog_index >= 0:
    prog_indices.append(prog_index)
    prog_index = halt['progenitor.co.index'][prog_index]
print(prog_indices)
print(halt['mass'][prog_indices])

# for the main progenitor, find its progenitors, list their mass
hindex = prog_indices[0]
prog_index = halt['progenitor.main.index'][hindex]
prog_indices = []
while prog_index >= 0:
    prog_indices.append(prog_index)
    prog_index = halt['progenitor.co.index'][prog_index]
print(prog_indices)
print(halt['mass'][prog_indices])

In [ ]:
# example of walking the merger tree
# get list of main progenitors as far back as can go

hindex = 0
prog_main_index = hindex
prog_main_indices = []
while prog_main_index >= 0:
    prog_main_indices.append(prog_main_index)
    prog_main_index = halt['progenitor.main.index'][prog_main_index]

print(prog_main_indices)
print(halt['mass'][prog_main_indices])
print(halt['position'][prog_main_indices])

In [ ]:
# halt.prop() computes derived quantities and can make walking the halo merger tree much easier

# for halo with tree index = 0, get its main progenitors going back as far as can (including self)
hindex = 0
prog_indices = halt.prop('progenitor.main.indices', hindex)

# print mass history
print(prog_indices)
print(halt['mass'][prog_indices])

In [ ]:
# print stellar mass history - recall that not all snapshots necessarily have star particle information

print(halt['star.mass'][prog_indices])

In [ ]:
# you can do this for an array of halo indices as well
# it will return progenitor indices as 2-D array (halo number x progenitor number) with null values 
# (snapshot before a halo existed) as (safely) negative

hindices = np.where(halt['snapshot'] == 600)[0]
prog_indices = halt.prop('progenitor.main.indices', hindices)
print(prog_indices)

In [ ]:
# same for descendant halos (going forward in time as far as can)

hindices = np.where(halt['snapshot'] == 100)[0]
desc_indices = halt.prop('descendant.indices', hindices)
print(desc_indices)

In [ ]:
# alternately, get *all* of the progenitors at previous snapshot and print their masses

hindex = 2
prog_indices = halt.prop('progenitor.indices', hindex)

print(prog_indices)
print(halt['mass'][prog_indices])

In [ ]:
# this also works with an input list (array) of halos
# but now it returns a list of progenitor index arrays
# because each halo has a variable (and potentially unlimited) number of progenitors

hindices = np.where(halt['snapshot'] == 100)[0]
hindices = hindices[:10]
prog_indices = halt.prop('progenitor.indices', hindices)

print(prog_indices)

In [ ]:
# the halo catalogs contains history-based properties of each halo, such as peak mass or peak circular velocity
# you can use .prop() to compute these on the fly within the merger trees for any property
# you can get either the full history for that property or the peak (maximum) value
# again, you can do this for a single halo or an array of them

hindices = np.where(halt['snapshot'] == 600)[0]

# one halo
hindex = hindices[0]
print(halt.prop('mass.bound.history', hindex))
print(halt.prop('mass.bound.peak', hindex))

# array of halos
print(halt.prop('mass.bound.history', hindices))
print(halt.prop('mass.bound.peak', hindices))

# interfacting between halo catalog and merger trees

Each halo in the merger tree has a pointer to its array index in the halo catalog: 'catalog.index'

Conversely, each halo in the catalog has a pointer to its array index in the merger tree: 'tree.index'

You can use these to go back and forth between the two.

Note: halo merger tree ids/indices are unique across all snapshots, but halo catalog ids/indices are unique only at a given snapshot

In [ ]:
# read halo merger trees across all snapshots
halt = halo.io.IO.read_tree(simulation_directory=simulation_directory)

# read halo catalog at a snapshot
hal = halo.io.IO.read_catalogs('redshift', 2, simulation_directory=simulation_directory, species=None)

In [ ]:
# get index of the halo in the merger trees
cat_index = 100  # some halo of interest
print(hal['mass'][cat_index])
tree_index = hal['tree.index'][cat_index]
print(tree_index)
print(halt['mass'][tree_index])

In [ ]:
# conversely, starting from the halo merger tree, get index of the halo in the catalog
# because halo catalog indices are *not* unique across snapshots,
# you also need to use which snapshot index the halo points to

hindices = np.where(halt['snapshot'] == 172)[0]
tree_index = hindices[0]  # some halo of interest
print(halt['mass'][tree_index])
snapshot_index = halt['snapshot'][tree_index]  # index of snapshot in halo catalog
cat_index = halt['catalog.index'][tree_index]  # halo catalog index at snapshot
print(snapshot_index, cat_index)
print(hal['mass'][cat_index])

See halo.plot for examples of analyzing/plotting halos in the catalog and merger trees.

See utilities package for lower-level functions that may be useful.